apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  namespace: flink-k8s
spec:
  selector:
    component: jobmanager
  ports:
    - port: 6123
      targetPort: 6123
      name: flink
    - port: 7070
      targetPort: 7070
      name: blobserver

