apiVersion: v1
kind: Service
metadata:
  name: jobmanager
  namespace: flink-1
spec:
  selector:
    component: jobmanager
  ports:
    - port: 6123
      targetPort: 6123
      name: flink
    - port: 50101
      targetPort: 50101
      name: blobserver

