apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: tig
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
