apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: tig
spec:
#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:5.0.0
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 10Mi
      volumes:
      - name: grafana-data
        gcePersistentDisk:
          pdName: grafana-data
          fsType: ext4
