apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
  namespace: tig
spec:
#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          name: admin
        - containerPort: 8086
          name: http
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-data
        gcePersistentDisk:
          pdName: influxdb-1
          fsType: ext4
