#!/usr/bin/env bash

source ./config.sh
source ./scripts/attach.sh
source ./scripts/config.sh
source ./scripts/create.sh
source ./scripts/delete.sh
source ./scripts/update.sh
source ./scripts/deploy.sh

case $1 in
  attach)
    attach $2 $3
    exit 0
    ;;
  config)
    config $2 $3
    exit 0
    ;;
  create)
    create $2 $3
    exit 0
    ;;
  delete)
    delete $2 $3
    exit 0
    ;;
  deploy)
    deploy $2 $3
    exit 0
    ;;
  update)
    update $2 $3
    exit 0
    ;;
  *)
    echo "USAGE: $0 $1"
    echo ""
    attach-usage
    config-usage
    create-usage
    delete-usage
    deploy-usage
    update-usage
    exit 1
    ;;
esac  
