apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: telegraf
  name: telegraf
  namespace: tig
spec:
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          volumeMounts:
            - mountPath: /etc/telegraf
              name: telegraf
      volumes:
      - name: telegraf
        configMap:
          name: telegraf
