apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink
  labels:
    app: flink-taskmanager
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flink-taskmanager
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:latest
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        - containerPort: 8125
          name: metrics
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager