apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      hostNetwork: true
      containers:
      - name: taskmanager
        image: wuchangping/flink:1.6.0
        args:
        - taskmanager
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: http
 #       env:
 #       - name: JOB_MANAGER_RPC_ADDRESS
 #         value: flink-jobmanager
          
